**LabML04**

Explain the initial dataset

What type of transformation was performed?

What is the meaning of this transformation?

What other type of processing may be performed?

In [1]:
#invocar biblioteca sklearn e importar modulo PCA e pandas
from sklearn.decomposition import PCA
import pandas as pd

In [2]:
#ler um ficheiro csv e criar um df com os valores obtidos
df=pd.read_csv("https://raw.githubusercontent.com/masterfloss/data/main/worlddata.csv")
df

,Country,Area_km2,Birth rate(births/1000 population),Current account balance,Death rate(deaths/1000 population),Debt - external,Electricity - consumption(kWh),Electricity - production(kWh),Exports,GDP,...,Oil - production(bbl/day),Oil - proved reserves(bbl),Population,Public debt(% of GDP),Railways(km),Reserves of foreign exchange & gold,Telephones - main lines in use,Telephones - mobile cellular,Total fertility rate(children born/woman),Unemploy rate(%)
0,Afghanistan,647500,47.02,NaN,20.75,8.000000e+09,6.522000e+08,5.400000e+08,4.460000e+08,21500000000,...,0.0,0.000000e+00,29928987.0,NaN,NaN,NaN,33100.0,15000.0,6.75,NaN
1,Akrotiri,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rrrrr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,28748,15.08,-5.040000e+08,5.12,1.410000e+09,6.760000e+09,5.680000e+09,5.524000e+08,17460000000,...,2000.0,1.855000e+08,3563112.0,NaN,447.0,1.206000e+09,255000.0,1100000.0,2.04,14.8
3,Algeria,2381740,17.13,1.190000e+10,4.60,2.190000e+10,2.361000e+10,2.576000e+10,3.216000e+10,212000000000,...,1200000.0,1.187000e+10,32531853.0,37.4,3973.0,4.355000e+10,2199600.0,1447310.0,1.92,25.4
4,American Samoa,199,23.13,NaN,3.33,NaN,1.209000e+08,1.300000e+08,3.000000e+07,500000000,...,0.0,NaN,57881.0,NaN,NaN,NaN,15000.0,2377.0,3.25,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,West Bank,5860,32.37,NaN,3.99,1.080000e+08,NaN,NaN,2.050000e+08,1800000000,...,NaN,NaN,2385615.0,NaN,NaN,NaN,301600.0,480000.0,4.40,27.2
259,Western Sahara,266000,NaN,NaN,NaN,NaN,8.370000e+07,9.000000e+07,NaN,NaN,...,0.0,NaN,273008.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
260,Yemen,527970,43.07,3.699000e+08,8.53,5.400000e+09,2.827000e+09,3.040000e+09,4.468000e+09,16250000000,...,417500.0,4.000000e+09,20727063.0,46.4,NaN,5.300000e+09,542200.0,411100.0,6.67,35.0
261,Zambia,752614,41.38,-1.814000e+08,20.23,5.353000e+09,5.345000e+09,8.167000e+09,1.548000e+09,9409000000,...,0.0,NaN,11261795.0,127.5,2173.0,3.450000e+08,88400.0,241000.0,5.47,50.0
262,Zimbabwe,390580,29.74,-2.303000e+08,24.66,4.086000e+09,1.122000e+10,8.839000e+09,1.409000e+09,24370000000,...,0.0,NaN,12746990.0,52.3,3077.0,5.700000e+07,300900.0,379100.0,3.54,70.0

In [3]:
#Mostrar os tipos de dados das variaveis
df.dtypes

Country                                            object
Area_km2                                            int64
Birth rate(births/1000 population)                float64
Current account balance                           float64
Death rate(deaths/1000 population)                float64
Debt - external                                   float64
Electricity - consumption(kWh)                    float64
Electricity - production(kWh)                     float64
Exports                                           float64
GDP                                                object
GDPpercapita                                      float64
GDP - real growth rate(%)                         float64
HIV/AIDS - adult prevalence rate(%)               float64
HIV/AIDS - deaths                                 float64
HIV/AIDS - people living with HIV/AIDS            float64
Highways(km)                                      float64
Imports                                           float64
Industrial production growth rate(%)              float64
Infant mortality rate(deaths/1000 live births)    float64
Inflation rate (consumer prices)(%)               float64
Internet hosts                                    float64
Internet users                                    float64
Investment (gross fixed)(% of GDP)                float64
Labor force                                       float64
Life expectancy at birth(years)                   float64
Military expenditures - dollar figure             float64
MilitPercentGDP                                   float64
Natural gas - consumption(cu m)                   float64
Natural gas - exports(cu m)                       float64
Natural gas - imports(cu m)                       float64
Natural gas - production(cu m)                    float64
Natural gas - proved reserves(cu m)               float64
Oil - consumption(bbl/day)                        float64
Oil - exports(bbl/day)                            float64
Oil - imports(bbl/day)                            float64
Oil - production(bbl/day)                         float64
Oil - proved reserves(bbl)                        float64
Population                                        float64
Public debt(% of GDP)                             float64
Railways(km)                                      float64
Reserves of foreign exchange & gold               float64
Telephones - main lines in use                    float64
Telephones - mobile cellular                      float64
Total fertility rate(children born/woman)         float64
Unemploy rate(%)                                  float64
dtype: object

In [10]:
df['GDP']=pd.to_numeric(df['GDP'], downcast='float', errors='coerce')

In [5]:
#Apagar a variavel Country
df1=df.drop(['Country'], axis=1)

In [6]:
#remover todas as listas onde existem variaveis sem valores.
X=df1.dropna()
X

,Area_km2,Birth rate(births/1000 population),Current account balance,Death rate(deaths/1000 population),Debt - external,Electricity - consumption(kWh),Electricity - production(kWh),Exports,GDP,GDPpercapita,...,Oil - production(bbl/day),Oil - proved reserves(bbl),Population,Public debt(% of GDP),Railways(km),Reserves of foreign exchange & gold,Telephones - main lines in use,Telephones - mobile cellular,Total fertility rate(children born/woman),Unemploy rate(%)
15,83870,8.81,-3.283000e+09,9.70,1.550000e+10,5.509000e+10,5.849000e+10,1.030000e+11,2.560000e+11,31300.0,...,20670.0,8.569000e+07,8.184691e+06,64.2,6021.0,1.273000e+10,3881000.0,7094500.0,1.36,4.4
48,756950,15.44,2.185000e+09,5.76,4.460000e+10,4.180000e+10,4.860000e+10,2.920000e+10,1.690000e+11,10700.0,...,18500.0,1.500000e+08,1.598091e+07,12.8,6585.0,1.602000e+10,3467000.0,6445700.0,2.02,8.5
49,9596960,13.14,3.032000e+10,6.94,2.330000e+11,1.630000e+12,1.910000e+12,5.830000e+11,7.260000e+12,5600.0,...,3392000.0,1.774000e+10,1.306314e+09,31.4,70058.0,6.100000e+11,263000000.0,269000000.0,1.72,9.8
63,78866,9.07,-5.730000e+09,10.54,3.628000e+10,5.533000e+10,7.175000e+10,6.651000e+10,1.720000e+11,16800.0,...,7419.0,1.725000e+07,1.024114e+07,33.5,9520.0,3.278000e+10,3626000.0,9708700.0,1.20,10.6
64,43094,11.36,6.529000e+09,10.43,2.170000e+10,3.163000e+10,3.638000e+10,7.306000e+10,1.740000e+11,32200.0,...,346200.0,1.230000e+09,5.432335e+06,42.5,3002.0,3.798000e+10,3610100.0,4785300.0,1.74,6.2
95,131940,9.72,-8.000000e+09,10.15,6.723000e+10,4.742000e+10,4.722000e+10,1.550000e+10,2.260000e+11,21300.0,...,5992.0,4.500000e+06,1.066835e+07,112.0,2571.0,7.300000e+09,5205100.0,8936200.0,1.33,10.0
111,93030,9.76,-7.941000e+09,13.19,5.700000e+10,3.599000e+10,3.407000e+10,5.462000e+10,1.490000e+11,14900.0,...,41190.0,1.107000e+08,1.000684e+07,58.3,7937.0,1.480000e+10,3666400.0,6862800.0,1.32,5.9
114,1919440,20.71,7.338000e+09,6.25,1.420000e+11,9.235000e+10,1.100000e+11,6.986000e+10,8.270000e+11,3500.0,...,971000.0,4.900000e+09,2.419739e+08,56.2,6458.0,3.582000e+10,7750000.0,11700000.0,2.44,9.2
117,70280,14.47,-2.881000e+09,7.85,1.100000e+10,2.178000e+10,2.288000e+10,1.040000e+11,1.260000e+11,31900.0,...,0.0,0.000000e+00,4.015676e+06,31.2,3312.0,4.152000e+09,1955000.0,3400000.0,1.87,4.3
119,301230,8.89,-2.110000e+10,10.30,9.140000e+11,2.940000e+11,2.620000e+11,3.360000e+11,1.610000e+12,27700.0,...,79460.0,5.866000e+08,5.810303e+07,105.6,19507.0,6.150000e+10,26596000.0,55918000.0,1.28,8.6
126,92300,21.76,2.032000e+08,2.63,7.320000e+09,7.094000e+09,7.307000e+09,3.200000e+09,2.550000e+10,4500.0,...,40.0,4.450000e+05,5.759732e+06,85.8,505.0,5.457000e+09,622600.0,1325300.0,2.71,15.0
128,2717300,15.78,-3.902000e+07,9.46,2.603000e+10,6.221000e+10,6.682000e+10,1.847000e+10,1.180000e+11,7800.0,...,1200000.0,2.600000e+10,1.518584e+07,13.7,13601.0,1.435000e+10,2081900.0,1027000.0,1.89,8.0
159,1972550,21.01,-4.113000e+09,4.73,1.500000e+11,1.900000e+11,2.040000e+11,1.820000e+11,1.010000e+12,9600.0,...,3460000.0,1.800000e+10,1.062029e+08,23.5,19510.0,6.067000e+10,15958700.0,28125000.0,2.45,3.2
175,268680,13.90,-3.647000e+09,7.53,4.734000e+10,3.571000e+10,3.839000e+10,1.985000e+10,9.251000e+10,23200.0,...,42160.0,8.962000e+07,4.035461e+06,22.1,3898.0,4.805000e+09,1765000.0,2599000.0,1.79,4.2
191,300000,25.31,3.600000e+09,5.47,5.560000e+10,4.605000e+10,5.286000e+10,3.863000e+10,4.310000e+11,5000.0,...,26000.0,1.520000e+08,8.785747e+07,74.2,897.0,1.605000e+10,3310900.0,15201000.0,3.16,11.7
193,312685,10.78,-3.831000e+09,10.01,9.915000e+10,1.170000e+11,1.340000e+11,7.598000e+10,4.630000e+11,12000.0,...,17180.0,1.164000e+08,3.863514e+07,49.9,23852.0,4.188000e+10,12300000.0,17401000.0,1.39,19.5
221,504782,10.10,-3.089000e+10,9.63,7.710000e+11,2.180000e+11,2.290000e+11,1.730000e+11,9.380000e+11,23300.0,...,7099.0,1.050000e+07,4.034146e+07,53.2,14268.0,1.970000e+10,17567500.0,37506700.0,1.28,10.4
248,244820,10.78,-3.346000e+10,10.18,4.710000e+12,3.370000e+11,3.960000e+11,3.470000e+11,1.780000e+12,29600.0,...,1957000.0,2.541000e+10,6.044146e+07,39.6,17186.0,4.873000e+10,34898000.0,49677000.0,1.66,4.8

In [7]:
#Criar um PCA que reduz o numero de features para 4
PCAModel = PCA(n_components=4)

#Transforma os features
XPCA = PCAModel.fit(X).transform(X)
XPCA

array([[-8.11310205e+11, -2.44286099e+11, -2.63822746e+11,
         2.88784206e+10],
       [-8.78747924e+11, -2.18412794e+11, -1.59191323e+11,
        -5.41190519e+10],
       [ 6.89976267e+12, -1.33912034e+12, -3.34945993e+11,
        -5.40285538e+10],
       [-8.89078309e+11, -2.14670378e+11, -2.59262711e+11,
        -2.98081729e+10],
       [-8.79856850e+11, -2.35605881e+11, -1.80923717e+11,
        -4.43280985e+09],
       [-8.50532368e+11, -1.91211290e+11, -2.68020895e+11,
        -4.24469194e+10],
       [-9.08015851e+11, -1.94137702e+11, -2.00526105e+11,
        -1.52467761e+10],
       [ 4.36558812e+11, -4.86185491e+11,  1.99715857e+12,
         6.75225402e+10],
       [-9.49792099e+11, -2.28681942e+11, -2.36351485e+11,
         2.11354311e+10],
       [ 7.23359291e+11,  4.36590876e+11, -4.41878648e+11,
         2.20440530e+11],
       [-1.05913189e+12, -2.23161771e+11, -2.06819406e+11,
        -6.23427510e+10],
       [-4.45540379e+11, -4.23082262e+11,  1.47114397e+12,
        -4.91530445e+10],
       [ 6.67885211e+10, -2.61696723e+11, -1.08015134e+11,
         1.01566183e+11],
       [-9.62575503e+11, -2.00323323e+11, -1.74634152e+11,
        -6.23269666e+10],
       [-6.38374577e+11, -2.42588239e+11, -2.21345987e+11,
        -1.42922384e+10],
       [-5.49475392e+11, -2.13178086e+11, -1.99285047e+11,
        -3.19239429e+10],
       [-1.30265214e+09,  4.02616278e+11, -4.51772863e+11,
         2.88249764e+10],
       [ 1.69726471e+12,  4.07713517e+12,  2.38493672e+11,
        -4.82468537e+10]])

In [8]:
#imprime o numero de fetures inicial e atual
print('Original number of features:', X.shape[1])
print('Reduced number of features:', XPCA.shape[1])

Original number of features: 44
Reduced number of features: 4

In [9]:
#Mostra o racio explicado por cada variavel
PCAModel.explained_variance_ratio_

array([0.68694987, 0.22798736, 0.08364335, 0.00101543])

**Explain the initial dataset**

R:No inicio é nos apresentado um conjunto de dados com 263 rows × 45 columns, onde a maioria das variaveis sao floats, havendo tambem objects e uma variaveil que é um integer

**What type of transformation was performed?**

R:Foi apagada a variavel Country, passando assim a ter 263 rows × 44 columns.
Depois foram removidas todas as listas onde existiam variaveis sem valores.
Depois foram reducidas o numero de variaveis para 4

**What is the meaning of this transformation?**

R:Com esta transformaçao retiram-se os dados que nao sao válidos na regressao, ficando apenas com as variaveis que mais explicam a variavel dependente.

**What other type of processing may be performed?**

R: POdiam ter sido feitas transformaçoes do tipo Linear Discriminant Analysis (LDA) , Non-negative Matrix Factorization e Truncate Singular Value Decomposition.